from typing import Protocol


class DataWriterProtocol(Protocol):
    def __init__(self, source_db_dsn: str, target_db_dsn: str): ...

    def write_data(self, *args, **kwargs): ...

    def __enter__(self): ...

    def __exit__(self, exc_type, exc_val, exc_tb): ...
